-- ============================================================
-- PT Merge Mining Industri — Procurement OLTP schema (PostgreSQL 14+)
--
-- Source of truth for the live app. ClickHouse keeps the same tables as the
-- analytics warehouse and is fed from here by db/ch_sync (see RUNBOOK).
--
-- Column names and meanings mirror db/clickhouse_schema.sql so API responses
-- and the warehouse sync stay 1:1. Differences from ClickHouse:
--   * no `version` columns — rows are updated in place
--   * real primary keys, foreign keys and unique constraints
--   * legacy_* ids (used in frontend URLs) come from identity sequences
--   * updated_at is maintained by trigger, so the sync can rely on it
--   * is_deleted stays a smallint 0/1 soft-delete flag, as in ClickHouse
--
-- Must run on PostgreSQL 14 (local dev) and 16 (mmi-postgres): no
-- NULLS NOT DISTINCT, no MERGE.
-- ============================================================

SET client_min_messages = warning;

-- ── Shared trigger: keep updated_at honest ───────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── Document number counters (PR-YYYY-NNN, PO-YYYY-NNN, ITEM-NNNN, V-NNNN) ───
-- Incremented with INSERT … ON CONFLICT DO UPDATE … RETURNING inside the
-- creating transaction, so two concurrent requests can never get the same
-- number. year = 0 for counters that do not reset yearly (ITEM, V).
CREATE TABLE IF NOT EXISTS doc_counters (
    doc_type   text     NOT NULL,
    year       integer  NOT NULL DEFAULT 0,
    last_no    integer  NOT NULL DEFAULT 0,
    PRIMARY KEY (doc_type, year)
);

-- ── Master data ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purposes (
    purpose_id   text        PRIMARY KEY,
    company_id   text        NOT NULL,
    label        text        NOT NULL,
    sort_order   integer     NOT NULL DEFAULT 0,
    status       text        NOT NULL DEFAULT 'active',
    is_deleted   smallint    NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
    user_id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_user_id  bigint      GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    company_id      text        NOT NULL,
    username        text        NOT NULL,
    password_hash   text        NOT NULL,
    role            text        NOT NULL CHECK (role IN ('requester', 'purchasing', 'md', 'admin')),
    full_name       text        NOT NULL DEFAULT '',
    email           text        NOT NULL DEFAULT '',
    department_id   text        NOT NULL DEFAULT '',
    status          text        NOT NULL DEFAULT 'active',
    is_deleted      smallint    NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
-- A deleted user's name may be reused; a live one may not.
CREATE UNIQUE INDEX IF NOT EXISTS users_live_username_uq
    ON users (company_id, username) WHERE is_deleted = 0;

CREATE TABLE IF NOT EXISTS vendors (
    vendor_id         text        PRIMARY KEY,
    company_id        text        NOT NULL,
    vendor_code       text        NOT NULL DEFAULT '',
    vendor_name       text        NOT NULL,
    category          text        NOT NULL DEFAULT '',
    status            text        NOT NULL DEFAULT 'active',
    contact_person    text        NOT NULL DEFAULT '',
    phone             text        NOT NULL DEFAULT '',
    mobile            text        NOT NULL DEFAULT '',
    email             text        NOT NULL DEFAULT '',
    address           text        NOT NULL DEFAULT '',
    city              text        NOT NULL DEFAULT '',
    country           text        NOT NULL DEFAULT 'ID',
    npwp              text        NOT NULL DEFAULT '',
    payment_term_id   text        NOT NULL DEFAULT '',
    default_currency  char(3)     NOT NULL DEFAULT 'IDR',
    tax_profile       text        NOT NULL DEFAULT '',
    risk_rating       text        NOT NULL DEFAULT '',
    onboarding_date   date,
    blocked_reason    text        NOT NULL DEFAULT '',
    search_text       text        NOT NULL DEFAULT '',
    is_deleted        smallint    NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS vendors_name_idx ON vendors (lower(vendor_name));

CREATE TABLE IF NOT EXISTS items (
    item_id                text          PRIMARY KEY,
    company_id             text          NOT NULL,
    base_item_id           text          NOT NULL DEFAULT '',
    item_code              text          NOT NULL DEFAULT '',
    name_en                text          NOT NULL DEFAULT '',
    name_cn                text          NOT NULL DEFAULT '',
    category_id            text          NOT NULL DEFAULT '',
    category_name          text          NOT NULL DEFAULT '',
    spec                   text          NOT NULL DEFAULT '',
    uom                    text          NOT NULL DEFAULT 'pcs',
    department_id          text          NOT NULL DEFAULT '',
    item_type              text          NOT NULL DEFAULT 'expense',
    default_gl_account_id  text          NOT NULL DEFAULT '',
    min_order_qty          numeric(18,4) NOT NULL DEFAULT 0,
    lead_time_days         integer       NOT NULL DEFAULT 0,
    status                 text          NOT NULL DEFAULT 'active',
    search_text            text          NOT NULL DEFAULT '',
    is_deleted             smallint      NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at             timestamptz   NOT NULL DEFAULT now(),
    updated_at             timestamptz   NOT NULL DEFAULT now()
);

-- ── Purchase requests ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_requests (
    pr_id                   uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_pr_id            bigint        GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    company_id              text          NOT NULL,
    pr_number               text          NOT NULL UNIQUE,
    requester_user_id       text          NOT NULL DEFAULT '',  -- legacy_user_id as text, as in ClickHouse
    requested_by_name       text          NOT NULL DEFAULT '',
    department_id           text          NOT NULL DEFAULT '',
    cost_center_id          text          NOT NULL DEFAULT '',
    pr_date                 date          NOT NULL DEFAULT CURRENT_DATE,
    needed_by_date          date,
    priority                text          NOT NULL DEFAULT 'normal',
    status                  text          NOT NULL DEFAULT 'draft',
    total_estimated_amount  numeric(18,2) NOT NULL DEFAULT 0,
    currency                char(3)       NOT NULL DEFAULT 'IDR',
    notes                   text          NOT NULL DEFAULT '',
    search_text             text          NOT NULL DEFAULT '',
    is_deleted              smallint      NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at              timestamptz   NOT NULL DEFAULT now(),
    updated_at              timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS pr_requester_idx ON purchase_requests (requester_user_id);

CREATE TABLE IF NOT EXISTS purchase_request_items (
    pr_item_id             uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_pr_item_id      bigint        GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    company_id             text          NOT NULL,
    pr_id                  uuid          NOT NULL REFERENCES purchase_requests (pr_id),
    line_no                integer       NOT NULL,
    item_id                text          NOT NULL REFERENCES items (item_id),
    item_description       text          NOT NULL DEFAULT '',
    requested_qty          numeric(18,4) NOT NULL,
    approved_qty           numeric(18,4) NOT NULL DEFAULT 0,
    uom                    text          NOT NULL DEFAULT 'pcs',
    estimated_unit_price   numeric(18,2) NOT NULL DEFAULT 0,
    estimated_total_price  numeric(18,2) NOT NULL DEFAULT 0,
    department_id          text          NOT NULL DEFAULT '',
    cost_center_id         text          NOT NULL DEFAULT '',
    gl_account_id          text          NOT NULL DEFAULT '',
    status                 text          NOT NULL DEFAULT 'pending',
    notes                  text          NOT NULL DEFAULT '',
    is_deleted             smallint      NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at             timestamptz   NOT NULL DEFAULT now(),
    updated_at             timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS pri_pr_idx   ON purchase_request_items (pr_id);
CREATE INDEX IF NOT EXISTS pri_item_idx ON purchase_request_items (item_id);

-- ── Purchase orders ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_orders (
    po_id                   uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_po_id            bigint        GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    company_id              text          NOT NULL,
    po_number               text          NOT NULL UNIQUE,
    primary_pr_id           uuid          REFERENCES purchase_requests (pr_id),  -- '' in ClickHouse ⇒ NULL here
    vendor_id               text          NOT NULL DEFAULT '',
    vendor_name             text          NOT NULL DEFAULT '',
    po_date                 date          NOT NULL DEFAULT CURRENT_DATE,
    expected_delivery_date  date,
    currency                char(3)       NOT NULL DEFAULT 'IDR',
    exchange_rate           numeric(18,6) NOT NULL DEFAULT 1,
    payment_term_id         text          NOT NULL DEFAULT '',
    status                  text          NOT NULL DEFAULT 'draft',
    subtotal_amount         numeric(18,2) NOT NULL DEFAULT 0,
    discount_amount         numeric(18,2) NOT NULL DEFAULT 0,
    charges_amount          numeric(18,2) NOT NULL DEFAULT 0,
    tax_amount              numeric(18,2) NOT NULL DEFAULT 0,
    withholding_amount      numeric(18,2) NOT NULL DEFAULT 0,
    total_amount            numeric(18,2) NOT NULL DEFAULT 0,
    notes                   text          NOT NULL DEFAULT '',
    search_text             text          NOT NULL DEFAULT '',
    created_by_user_id      text          NOT NULL DEFAULT '',
    is_deleted              smallint      NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at              timestamptz   NOT NULL DEFAULT now(),
    updated_at              timestamptz   NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
    po_item_id         uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_po_item_id  bigint        GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    company_id         text          NOT NULL,
    po_id              uuid          NOT NULL REFERENCES purchase_orders (po_id),
    line_no            integer       NOT NULL,
    pr_item_id         uuid          REFERENCES purchase_request_items (pr_item_id),  -- '' ⇒ NULL
    quotation_item_id  text          NOT NULL DEFAULT '',
    item_id            text          NOT NULL REFERENCES items (item_id),
    item_description   text          NOT NULL DEFAULT '',
    ordered_qty        numeric(18,4) NOT NULL,
    received_qty       numeric(18,4) NOT NULL DEFAULT 0,
    invoiced_qty       numeric(18,4) NOT NULL DEFAULT 0,
    uom                text          NOT NULL DEFAULT 'pcs',
    unit_price         numeric(18,2) NOT NULL,
    discount_amount    numeric(18,2) NOT NULL DEFAULT 0,
    tax_amount         numeric(18,2) NOT NULL DEFAULT 0,
    total_price        numeric(18,2) NOT NULL,
    gl_account_id      text          NOT NULL DEFAULT '',
    cost_center_id     text          NOT NULL DEFAULT '',
    vendor_name        text          NOT NULL DEFAULT '',
    status             text          NOT NULL DEFAULT 'open',
    notes              text          NOT NULL DEFAULT '',
    purpose            text          NOT NULL DEFAULT '',
    is_deleted         smallint      NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at         timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS poi_po_idx     ON purchase_order_items (po_id);
CREATE INDEX IF NOT EXISTS poi_pritem_idx ON purchase_order_items (pr_item_id);

CREATE TABLE IF NOT EXISTS purchase_order_charges (
    charge_id        uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id       text          NOT NULL,
    po_id            uuid          NOT NULL REFERENCES purchase_orders (po_id),
    line_no          integer       NOT NULL DEFAULT 0,
    charge_type      text          NOT NULL DEFAULT 'other',
    description      text          NOT NULL DEFAULT '',
    amount           numeric(18,2) NOT NULL DEFAULT 0,
    gl_account_code  text          NOT NULL DEFAULT '',
    is_taxable       smallint      NOT NULL DEFAULT 1,
    is_deleted       smallint      NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS poc_po_idx ON purchase_order_charges (po_id);

-- ── Append-only logs (MergeTree in ClickHouse) ───────────────────────────────
-- document_id / document_item_id stay text: they hold PR or PO uuids depending
-- on document_type, so a single foreign key cannot cover them.
CREATE TABLE IF NOT EXISTS approval_actions (
    approval_action_id  uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id          text          NOT NULL,
    document_type       text          NOT NULL,
    document_id         text          NOT NULL,
    document_item_id    text          NOT NULL DEFAULT '',
    workflow_id         text          NOT NULL DEFAULT '',
    step_no             integer       NOT NULL DEFAULT 0,
    actor_user_id       text          NOT NULL DEFAULT '',
    actor_name          text          NOT NULL DEFAULT '',
    action              text          NOT NULL,
    action_at           timestamptz   NOT NULL DEFAULT now(),
    from_status         text          NOT NULL DEFAULT '',
    to_status           text          NOT NULL DEFAULT '',
    approved_qty        numeric(18,4),
    notes               text          NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS aa_doc_idx ON approval_actions (document_type, document_id, action_at);

CREATE TABLE IF NOT EXISTS gl_exports (
    gl_export_id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_log_id         bigint,
    company_id            text        NOT NULL,
    source_document_type  text        NOT NULL,
    source_document_id    text        NOT NULL,
    export_number         text        NOT NULL DEFAULT '',
    export_date           date        NOT NULL DEFAULT CURRENT_DATE,
    filename              text        NOT NULL,
    status                text        NOT NULL DEFAULT 'generated',
    exported_by_user_id   text        NOT NULL DEFAULT '',
    notes                 text        NOT NULL DEFAULT '',
    created_at            timestamptz NOT NULL DEFAULT now()  -- not in ClickHouse; sync watermark only
);

-- ── Item requests & PR templates (created at runtime by server.js before) ────
CREATE TABLE IF NOT EXISTS item_requests (
    request_id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id            text        NOT NULL,
    requested_by_user_id  text        NOT NULL DEFAULT '',
    requested_by_name     text        NOT NULL DEFAULT '',
    name_en               text        NOT NULL DEFAULT '',
    name_cn               text        NOT NULL DEFAULT '',
    category_name         text        NOT NULL DEFAULT '',
    spec                  text        NOT NULL DEFAULT '',
    uom                   text        NOT NULL DEFAULT 'pcs',
    notes                 text        NOT NULL DEFAULT '',
    source_excel_name     text        NOT NULL DEFAULT '',
    status                text        NOT NULL DEFAULT 'pending',
    approved_item_id      text        NOT NULL DEFAULT '',
    admin_notes           text        NOT NULL DEFAULT '',
    is_deleted            smallint    NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pr_templates (
    template_id    text        PRIMARY KEY,
    company_id     text        NOT NULL,
    template_name  text        NOT NULL DEFAULT '',
    display_name   text        NOT NULL DEFAULT '',
    sort_order     integer     NOT NULL DEFAULT 0,
    is_deleted     smallint    NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- item_id is free text here (not a foreign key): templates were imported from
-- Excel and may name items that were later merged or removed.
CREATE TABLE IF NOT EXISTS pr_template_items (
    template_item_id  text          PRIMARY KEY,
    company_id        text          NOT NULL,
    template_id       text          NOT NULL REFERENCES pr_templates (template_id),
    item_id           text          NOT NULL DEFAULT '',
    name_en           text          NOT NULL DEFAULT '',
    name_cn           text          NOT NULL DEFAULT '',
    spec              text          NOT NULL DEFAULT '',
    department        text          NOT NULL DEFAULT '',
    uom               text          NOT NULL DEFAULT '',
    default_qty       numeric       NOT NULL DEFAULT 0,  -- Float64 in ClickHouse
    sort_order        integer       NOT NULL DEFAULT 0,
    is_deleted        smallint      NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
    created_at        timestamptz   NOT NULL DEFAULT now(),
    updated_at        timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS pti_template_idx ON pr_template_items (template_id);

-- ── Sessions (connect-pg-simple's expected layout) ───────────────────────────
CREATE TABLE IF NOT EXISTS session (
    sid     varchar      NOT NULL PRIMARY KEY,
    sess    json         NOT NULL,
    expire  timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS session_expire_idx ON session (expire);

-- ── updated_at triggers + sync indexes on every mutable table ────────────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'purposes', 'users', 'vendors', 'items', 'purchase_requests',
    'purchase_request_items', 'purchase_orders', 'purchase_order_items',
    'purchase_order_charges', 'item_requests', 'pr_templates', 'pr_template_items'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I_set_updated_at ON %I', t, t);
    EXECUTE format('CREATE TRIGGER %I_set_updated_at BEFORE UPDATE ON %I
                    FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (updated_at)', t || '_updated_at_idx', t);
  END LOOP;
END $$;
